import { Region } from '../types'

/**
 * Configuration for constructing the CommercetoolsAuth class.
 *
 *
 */
export interface CommercetoolsAuthConfig {
  projectKey: string
  clientId: string
  clientSecret: string
  region: Region
  refreshIfWithinSecs?: number
  clientScopes: string[]
  customerScopes?: string[]
  timeout?: number
  logger?: {
    debug: (...args: any) => void
    info: (...args: any) => void
    error: (...args: any) => void
  }
}

export interface CommercetoolsAuthApiConfig {
  projectKey: string
  clientId: string
  clientSecret: string
  region: Region
  timeout?: number
  logger?: {
    debug: (...args: any) => void
    info: (...args: any) => void
    error: (...args: any) => void
  }
}

/**
 * The object structure that we receive back from commercetools
 * on a successful call to get a new token.
 */
export interface CommercetoolsGrantResponse extends CommercetoolsRefreshGrantResponse {
  refresh_token: string
}

export interface CommercetoolsRefreshGrantResponse {
  access_token: string
  expires_in: number
  scope: string
}

/**
 * The structure of an object transformed from the data that we receive back
 * from commercetools when hitting the `/oauth/token` endpoint with the `grant_type`
 * set to {@link GrantType.REFRESH_TOKEN}.
 */
export interface RefreshedAccessToken {
  /**
   * The access token string needed when making requests to commercetools. If this
   * was generated by a customer logging in, then this is used by commercetools
   * to identify the customer.
   */
  accessToken: string

  /**
   * The duration of the access token in seconds (typically 48 hours)
   */
  expiresIn: number

  /**
   * This is the expiry date/time of the access token. This is calculated based
   * on the `expiredIn` property, and as such may be very slightly after the
   * internal commercetools expiry date (due to the time involved to receive
   * and process the response.
   */
  expiresAt: Date

  /**
   * List of permission scopes. This will also include the `anonymous_id` when
   * generating an anonymous customer token, or the `customer_id` when logging
   * in as an existing customer.
   */
  scopes: string[]
}

/**
 * The structure of an object transformed from the data that we receive back
 * from commercetools when hitting the `/oauth/token` endpoint with the `grant_type`
 * set to {@link GrantType.CLIENT_CREDENTIALS} or {@link GrantType.PASSWORD}.
 */
export interface AccessToken extends RefreshedAccessToken {
  refreshToken: string
}

/**
 * This is the LoginOptions description
 */
export interface LoginOptions {
  /**
   * The customer's username (email address)
   */
  username: string

  /**
   * The customer's password
   */
  password: string

  /**
   * The scopes to which you want to restrict the customer token. Note that
   * these must be a subset of the scopes associated with the client id/secret.
   */
  scopes?: string[]
}

export interface AnonymousTokenOptions {
  /**
   * The scopes of the anonymous customer must be less than or equal to
   * the scopes of the client API key (ideally, less). If you don't specify
   * the scopes using this property, then the code will check for the scopes
   * defined on {@link CommercetoolsAuthConfig.customerScopes}. If scopes
   * aren't defined there either, than an error will be thrown when a call
   * is made to {@link CommercetoolsAuth.getAnonymousGrant}
   */
  scopes?: string[]
  /**
   * If you specify this, you need to be sure that the value does not
   * already exist as an anonymous customer id in the commercetools system
   * under your project key. If it does, an error will be thrown when
   * trying to create the access token.
   */
  anonymousId?: string
}

/**
 * Authentication grant types.
 * These are used when populating the 'grant_type' parameter.
 */
export enum GrantType {
  /**
   * Used when either requesting a client access token or an
   * anonymous customer access token:
   * https://docs.commercetools.com/api/authorization#client-credentials-flow
   * https://docs.commercetools.com/api/authorization#tokens-for-anonymous-sessions
   */
  CLIENT_CREDENTIALS = 'client_credentials',
  /**
   * Used when refreshing any existing access token (whether client or customer):
   * https://docs.commercetools.com/api/authorization#refresh-token-flow
   */
  REFRESH_TOKEN = 'refresh_token',
  /**
   * Used when attempting to login a customer:
   * https://docs.commercetools.com/api/authorization#password-flow
   */
  PASSWORD = 'password'
}
