coverage:
  status:
    project:
      default:
        target: 99%
        threshold: 0%
    patch:
      default:
        target: 99%
        threshold: 0%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

